### ISSUE TITLE
Just a couple of questions.

### ISSUE THREAD

**Issue by virtualdogbert** [rapid7/r7insight_java#27]
Hi just a couple of questions I didn't find documentation currently we are using:
compile "com.logentries:logentries-appender:1.1.32"
but it looks like from the repos we should upgrade to
com.rapid:r7insight_java:3.0.13
For use with logback?

Also is this appender async by default or should we be using logback's AsyncAppender in conjunction with the logentries appender?
I ask because one of my coworkers said he thought it was async, but I couldn't find any evidence in documentation that it was without the AsyncAppender. However I just looked at the code and it looks like it probably is. So that would be good to add to the documentation.

**Comment by jcolgan-r7** [comment]
Hey @virtualdogbert!
r7insight_java:3.0.13 does indeed sound like the right upgrade for you. Please note we've just now released this version, so it may take a few hours to become available in Maven central.
The logback appender is asynchronous by itself, as you suggest.
